services:
  searchtest01:
    image: ghcr.io/codelibs/fess-opensearch:3.1.0
    container_name: searchtest01
    environment:
      - node.name=searchtest01
      - discovery.seed_hosts=searchtest01
      - cluster.initial_cluster_manager_nodes=searchtest01
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - node.roles=cluster_manager,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
#    ports:
#      - 9200:9200
    networks:
      - searchtestnet
