services:
  estest01:
    image: ghcr.io/codelibs/fess-opensearch:2.17.0
    container_name: estest01
    environment:
      - node.name=estest01
      - discovery.seed_hosts=estest01
      - cluster.initial_cluster_manager_nodes=estest01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "FESS_DICTIONARY_PATH=/usr/share/opensearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
#    ports:
#      - 9200:9200
    networks:
      - estestnet
