services:
  fesstest01:
    image: ghcr.io/codelibs/fess:14.6.0
    container_name: fesstest01
    environment:
      - "ES_HTTP_URL=http://estest01:9200"
      - "FESS_DICTIONARY_PATH=${FESS_DICTIONARY_PATH:-/usr/share/elasticsearch/config/dictionary/}"
#    ports:
#      - "8080:8080"
    networks:
      - estestnet
    depends_on:
      - estest01
