services:
  searchtest01:
    image: ghcr.io/codelibs/fess-elasticsearch:8.12.2
    container_name: searchtest01
    environment:
      - node.name=searchtest01
      - discovery.seed_hosts=searchtest01
      - cluster.initial_master_nodes=searchtest01
      - cluster.name=fess-search
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
#    ports:
#      - 9200:9200
    networks:
      - searchtestnet
