version: "3"
services:
  test01:
    build: .
    container_name: test01
    environment:
      - "FESS_URL=http://fess01:8080"
      - "BROWSER_LOCALE=ja-JP"
      - "HEADLESS=true"
    networks:
      - esnet
    depends_on:
      - fess01

networks:
  esnet:
    driver: bridge

