name: run-fessx-noble-opensearch3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fessx-noble opensearch3