name: run-fess15-al2023-opensearch3

on:
  schedule:
    - cron: '0 0 * * 1'  # Monday (secondary)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fess15-al2023 opensearch3