name: run-fess13-opensearch1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fess13 opensearch1
