name: run-fess14-elasticsearch7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fess14 elasticsearch7
