name: run-fessx-opensearch1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fessx opensearch1
