name: run-fess15-al2023-opensearch2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 16 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-compose
        shell: bash
        run: |
          /bin/bash ./run_test.sh fess15-al2023 opensearch2
